@startuml

class Abenteurer
class Fertigkeit
class Gegenstand
class Hintergrund
class Klasse
class Merkmal
class Merkmalliste
class MerkmalUebung
class MerkmalUebungFertigkeit
class MerkmalUebungGegenstand
class Volk
class Zauber
class Zauberliste

Abenteurer "*" -- "1" Hintergrund
Abenteurer "*" -- "*" Fertigkeit
Abenteurer "*" -- "*" Gegenstand
Abenteurer "*" -- "*" Klasse
Abenteurer "*" -- "*" Merkmal
Abenteurer "*" -- "1" Volk
Abenteurer "*" -- "*" Zauber

Gegenstand <|-- Ruestung
Gegenstand <|-- Waffe

Hintergrund "*" -- "*" Merkmal

Klasse "*" -- "*" Merkmal

Merkmal <|-- MerkmalFertigkeit
Merkmal <|-- Merkmalliste
Merkmal <|-- MerkmalRuestungsklasse
Merkmal <|-- MerkmalUebung
Merkmal <|-- MerkmalZauber

Merkmalliste "*" -- "*" Merkmal

MerkmalUebungFertigkeit "1" -- "1" Fertigkeit
MerkmalUebungGegenstand "1" -- "1" Gegenstand

MerkmalUebung <|-- MerkmalUebungFertigkeit
MerkmalUebung <|-- MerkmalUebungGegenstand

Volk "*" -- "*" Merkmal

Zauber "*" -- "*" Zauberliste


Zauberliste "*" -- "1" Klasse

@enduml